#配置项目访问端口
server: 
  port: 9081

# DATASOURCE  
jdbc:  
    driverClass: com.mysql.jdbc.Driver  
    url: jdbc:mysql://127.0.0.1:3306/newtranx?useUnicode=true&characterEncoding=utf8
    username: root 
    password: root
    #定义初始连接数
    initialSize: 5
    #定义最大连接数
    maxActive: 20
    #定义最大空闲
    maxIdle: 2
    #定义最小空闲
    minIdle: 1
    #定义最长等待时间
    maxWait: 60000
    
# SPRING PROFILES  
spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
 # MyBatis  
mybatis:  
    typeAliasesPackage: com.newtranx.index.entity
    mapperLocations: classpath*:com/newtranx/index/mapper/*.xml  
